/**
 * PRD-007 Volume-1 §7 — platform-level permissions, fully independent of
 * the tenant `Permission` enum/`PERMISSION_MATRIX`. Do not add a permission
 * here without an approved Business Decision (same discipline as
 * `permission.enum.ts`).
 */
export enum PlatformPermission {
  VIEW_PLATFORM_DASHBOARD = "VIEW_PLATFORM_DASHBOARD",
  VIEW_WORKSPACES = "VIEW_WORKSPACES",
  MANAGE_WORKSPACE_STATUS = "MANAGE_WORKSPACE_STATUS",
  MANAGE_PLATFORM_USERS = "MANAGE_PLATFORM_USERS",
  MANAGE_ANNOUNCEMENTS = "MANAGE_ANNOUNCEMENTS",
  MANAGE_PLATFORM_FEATURE_FLAGS = "MANAGE_PLATFORM_FEATURE_FLAGS",
  VIEW_PLATFORM_SEARCH = "VIEW_PLATFORM_SEARCH",
  MANAGE_PLATFORM_MAINTENANCE = "MANAGE_PLATFORM_MAINTENANCE",
  // PRD-007 Volume-2 (Platform Billing Operations & Customer Support).
  VIEW_PLATFORM_BILLING = "VIEW_PLATFORM_BILLING",
  MANAGE_SUBSCRIPTIONS = "MANAGE_SUBSCRIPTIONS",
  MANAGE_PAYMENTS = "MANAGE_PAYMENTS",
  MANAGE_SUPPORT = "MANAGE_SUPPORT",
  MANAGE_TRIALS = "MANAGE_TRIALS",
}
