// @wapp/config — Next.js 15 App Router ESLint extension
import { baseConfig } from "./base.mjs";

/** @type {import("eslint").Linter.Config[]} */
export const nextConfig = [
  ...baseConfig,
  {
    rules: {
      // DS-001 / TAD-001: Pages Router is prohibited — App Router only.
      // Enforced structurally (no /pages directory should exist); this rule
      // block is the documented place that decision lives for lint tooling.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } }, // allow async Server Actions passed as event handlers
      ],
    },
  },
  {
    // next-env.d.ts is auto-generated by Next.js itself (its triple-slash
    // reference is required, not a lint violation) — caught by actually
    // running lint after `next build` generated the file, not by inspecting
    // the config in isolation.
    ignores: ["next-env.d.ts"],
  },
];

export default nextConfig;
